# PY HACK 2021

Importing libraries and reading data files

In [23]:
%matplotlib inline
import warnings 
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

loading of data

In [29]:
# loading of data
Adverse_events=pd.read_csv("AE_data_sample.csv")
Concomitant_Medications=pd.read_csv("cm_data_sample.csv")

In [32]:
print(Adverse_events.shape)
print(Concomitant_Medications.shape)

(49, 88)
(50, 49)

In [39]:
#display
Adverse_events.tail(5)

,STUDYID,SITEID,SUBJID,SUBJECTID,VISITINDEX,VISITNAM,FORMNAME,FORMID,FORMIDX,FORMINDEX,...,AEACN3_C,AEACN3,AEACN3_1_C,AEACN3_1,AERELNST_C,AERELNST,AERELNST_ND,AERELT,AEOUT_C,AEOUT
44,StudyHack,5538,55385052,2978591,1,AECM,AE202,38768,31,5.840000e+14,...,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
45,StudyHack,5538,55385052,2978591,1,AECM,AE202,38768,32,5.840000e+14,...,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
46,StudyHack,5538,55385052,2978591,1,AECM,AE202,38768,33,5.840000e+14,...,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
47,StudyHack,5538,55385052,2978591,1,AECM,AE202,38768,34,5.840000e+14,...,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
48,StudyHack,5538,55385052,2978591,1,AECM,AE202,38768,35,5.840000e+14,...,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED

In [35]:
Concomitant_Medications.head(10)

,STUDYID,SITEID,SUBJID,SUBJECTID,VISITID,VISITIDX,VISITNAM,FORMNAME,FORMID,FORMIDX,...,CMSTDAT_DTS,CMENDAT,CMENDAT_DTR,CMENDAT_DTS,CMONGO,CMONGO_C,CMONGO_ND,COMPTERM,CMDECOD,SITENO
0,StudyHack,5163,51635003,851940,38942,1,AECM,CM201,38623,13,...,21/09/2018,50/5/2018,50/5/2018,50/5/2018,NO,N,NaN,AMIPAREN,ALANINE;ARGININE;ASPARTIC ACID;CYSTEINE;GLUTAM...,53301
1,StudyHack,5163,51635003,851940,38942,1,AECM,CM201,38623,14,...,50/30/2018,51/2/2018,51/2/2018,51/2/2018,NO,N,NaN,GRANISETRON HYDROCHLORIDE,GRANISETRON HYDROCHLORIDE,53301
2,StudyHack,5163,51635003,851940,38942,1,AECM,CM201,38623,53,...,51/5/2018,51/7/2018,51/7/2018,51/7/2018,NO,N,NaN,GRANISETRON HYDROCHLORIDE,GRANISETRON HYDROCHLORIDE,53301
3,StudyHack,5163,51635003,851940,38942,1,AECM,CM201,38623,16,...,50/9/2018,50/19/2018,50/19/2018,50/19/2018,NO,N,NaN,PAREPLUS,ACETYLCYSTEINE;ALANINE;ARGININE;ASCORBIC ACID;...,53301
4,StudyHack,5163,51635003,851940,38942,1,AECM,CM201,38623,17,...,50/22/2018,51/13/2018,51/13/2018,51/13/2018,NO,N,NaN,PAREPLUS,ACETYLCYSTEINE;ALANINE;ARGININE;ASCORBIC ACID;...,53301
5,StudyHack,5163,51635003,851940,38942,1,AECM,CM201,38623,18,...,08/09/2018,50/5/2018,50/5/2018,50/5/2018,NO,N,NaN,ELNEOPA-NF NO.2,AMINO ACIDS NOS;COPPER;ELECTROLYTES NOS;GLUCOS...,53301
6,StudyHack,5163,51635003,851940,38942,1,AECM,CM201,38623,20,...,26/09/2018,50/4/2018,50/4/2018,50/4/2018,NO,N,NaN,CASPOFUNGIN ACETATE,CASPOFUNGIN ACETATE,53301
7,StudyHack,5163,51635003,851940,38942,1,AECM,CM201,38623,21,...,50/2/2018,50/2/2018,50/2/2018,50/2/2018,NO,N,NaN,D-CHLORPHENIRAMINE MALEATE,DEXCHLORPHENIRAMINE MALEATE,53301
8,StudyHack,5163,51635003,851940,38942,1,AECM,CM201,38623,22,...,50/2/2018,50/2/2018,50/2/2018,50/2/2018,NO,N,NaN,HYDROCORTISONE SODIUM SUCCINATE,HYDROCORTISONE SODIUM SUCCINATE,53301
9,StudyHack,5163,51635003,851940,38942,1,AECM,CM201,38623,23,...,16/08/2018,50/5/2018,50/5/2018,50/5/2018,NO,N,NaN,DEFEROXAMINE MESILATE,DEFEROXAMINE MESILATE,53301

In [36]:
Adverse_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 88 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   STUDYID      49 non-null     object
 1   SITEID       49 non-null     int64
 2   SUBJID       49 non-null     int64
 3   SUBJECTID    49 non-null     int64
 4   VISITINDEX   49 non-null     int64
 5   VISITNAM     49 non-null     object
 6   FORMNAME     49 non-null     object
 7   FORMID       49 non-null     int64
 8   FORMIDX      49 non-null     int64
 9   FORMINDEX    49 non-null     float64
 10  DOV          0 non-null      float64
 11  AEMEYN       33 non-null     object
 12  AEMEYN_C     33 non-null     object
 13  AECAT        34 non-null     object
 14  AECAT_C      34 non-null     float64
 15  AETERM       47 non-null     object
 16  AEMEDRG      31 non-null     object
 17  AEINPKG      11 non-null     float64
 18  AESTDAT      47 non-null     object
 19  AESTDAT_DTS  47 non-null     object
 20  AESTDAT_ND   2 non-null      object
 21  AESTDME      31 non-null     object
 22  AESTDME_C    31 non-null     float64
 23  AEENDAT      47 non-null     object
 24  AEENDAT_DTS  47 non-null     object
 25  AEENDAT_ND   2 non-null      object
 26  AEDIS        47 non-null     object
 27  AEDIS_C      47 non-null     object
 28  AEMERAE      31 non-null     object
 29  AEMERAE_C    31 non-null     object
 30  AESPID       16 non-null     float64
 31  AENDGIV      47 non-null     object
 32  AENDGIV_C    47 non-null     object
 33  AECMGIV      47 non-null     object
 34  AECMGIV_C    47 non-null     object
 35  AECMGIV_ND   2 non-null      object
 36  AEREFID      0 non-null      float64
 37  COMPTERM     47 non-null     object
 38  AELLT        47 non-null     object
 39  AEDECOD      47 non-null     object
 40  AEHLT        47 non-null     object
 41  AEHLGT       47 non-null     object
 42  AESOC        47 non-null     object
 43  AEMEDRG_C    31 non-null     float64
 44  AESPID_1     18 non-null     float64
 45  AEYN         16 non-null     object
 46  AEYN_C       16 non-null     object
 47  AEONGO_C     16 non-null     object
 48  AEONGO       16 non-null     object
 49  AETOXGR_C    16 non-null     float64
 50  AETOXGR      16 non-null     float64
 51  AESER_C      16 non-null     object
 52  AESER        16 non-null     object
 53  AERME_C      16 non-null     object
 54  AERME        16 non-null     object
 55  AETRT1       16 non-null     object
 56  AETRT3_C     16 non-null     float64
 57  AEREL1_C     16 non-null     float64
 58  AEREL1       16 non-null     object
 59  AEREL1_ND    0 non-null      float64
 60  AEACN1_C     15 non-null     float64
 61  AEACN1       15 non-null     object
 62  AEACN1_1_C   1 non-null      float64
 63  AEACN1_1     1 non-null      object
 64  AETRT2       16 non-null     object
 65  AETRT2_ND    0 non-null      float64
 66  AETRT2_C     16 non-null     float64
 67  AEREL2_C     16 non-null     float64
 68  AEREL2       16 non-null     object
 69  AEREL2_ND    0 non-null      float64
 70  AEACN2_C     10 non-null     float64
 71  AEACN2       10 non-null     object
 72  AEACN2_1_C   6 non-null      float64
 73  AEACN2_1     6 non-null      object
 74  AETRT3       16 non-null     object
 75  AETRT1_C     16 non-null     float64
 76  AEREL3_C     16 non-null     float64
 77  AEREL3       16 non-null     object
 78  AEACN3_C     15 non-null     float64
 79  AEACN3       15 non-null     object
 80  AEACN3_1_C   1 non-null      float64
 81  AEACN3_1     1 non-null      object
 82  AERELNST_C   1 non-null      float64
 83  AERELNST     1 non-null      object
 84  AERELNST_ND  0 non-null      float64
 85  AERELT       1 non-null      object
 86  AEOUT_C      16 non-null     float64
 87  AEOUT        16 non-null     object
dtypes: float64(29), int64(6), object(53)
memory usage: 33.8+ KB

In [37]:
Concomitant_Medications.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 49 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   STUDYID      50 non-null     object
 1   SITEID       50 non-null     int64
 2   SUBJID       50 non-null     int64
 3   SUBJECTID    50 non-null     int64
 4   VISITID      50 non-null     int64
 5   VISITIDX     50 non-null     int64
 6   VISITNAM     50 non-null     object
 7   FORMNAME     50 non-null     object
 8   FORMID       50 non-null     int64
 9   FORMIDX      50 non-null     int64
 10  FORMINDEX    50 non-null     float64
 11  CMYN         50 non-null     object
 12  CMYN_C       50 non-null     object
 13  CMCAT_C      50 non-null     int64
 14  CMCAT_ND     0 non-null      float64
 15  CMSCAT       0 non-null      float64
 16  CMSCAT_C     0 non-null      float64
 17  CMPRESP      50 non-null     object
 18  CMPRESP_C    50 non-null     object
 19  CMPRESP_ND   0 non-null      float64
 20  CMTRT        50 non-null     object
 21  CMTRT_ND     0 non-null      float64
 22  CMRGM        0 non-null      float64
 23  CMRGM_ND     0 non-null      float64
 24  CMINDC       0 non-null      float64
 25  CMAENO       10 non-null     float64
 26  CMAER        50 non-null     object
 27  CMAER_C      50 non-null     object
 28  CMDOSTOT     28 non-null     float64
 29  CMDOSTOT_ND  0 non-null      float64
 30  CMDOSU       28 non-null     object
 31  CMDOSU_C     28 non-null     float64
 32  CMDOSU_ND    0 non-null      float64
 33  CMROUTE      0 non-null      float64
 34  CMROUTE_C    0 non-null      float64
 35  CMPRIOR      50 non-null     object
 36  CMPRIOR_C    50 non-null     object
 37  CMSTDAT      46 non-null     object
 38  CMSTDAT_DTR  50 non-null     object
 39  CMSTDAT_DTS  50 non-null     object
 40  CMENDAT      40 non-null     object
 41  CMENDAT_DTR  40 non-null     object
 42  CMENDAT_DTS  40 non-null     object
 43  CMONGO       50 non-null     object
 44  CMONGO_C     50 non-null     object
 45  CMONGO_ND    0 non-null      float64
 46  COMPTERM     50 non-null     object
 47  CMDECOD      50 non-null     object
 48  SITENO       50 non-null     int64
dtypes: float64(17), int64(9), object(23)
memory usage: 19.3+ KB

In [43]:
Adverse_events.nunique()

STUDYID         1
SITEID         17
SUBJID         21
SUBJECTID      21
VISITINDEX      1
               ..
AERELNST        1
AERELNST_ND     0
AERELT          1
AEOUT_C         1
AEOUT           1
Length: 88, dtype: int64

In [44]:
Adverse_events.isnull().sum()

STUDYID         0
SITEID          0
SUBJID          0
SUBJECTID       0
VISITINDEX      0
               ..
AERELNST       48
AERELNST_ND    49
AERELT         48
AEOUT_C        33
AEOUT          33
Length: 88, dtype: int64

In [45]:
Concomitant_Medications.nunique()

STUDYID         1
SITEID          7
SUBJID          7
SUBJECTID       7
VISITID         1
VISITIDX        1
VISITNAM        1
FORMNAME        1
FORMID          1
FORMIDX        39
FORMINDEX      10
CMYN            1
CMYN_C          1
CMCAT_C         2
CMCAT_ND        0
CMSCAT          0
CMSCAT_C        0
CMPRESP         1
CMPRESP_C       1
CMPRESP_ND      0
CMTRT          42
CMTRT_ND        0
CMRGM           0
CMRGM_ND        0
CMINDC          0
CMAENO         10
CMAER           2
CMAER_C         2
CMDOSTOT       19
CMDOSTOT_ND     0
CMDOSU          4
CMDOSU_C        4
CMDOSU_ND       0
CMROUTE         0
CMROUTE_C       0
CMPRIOR         2
CMPRIOR_C       2
CMSTDAT        36
CMSTDAT_DTR    38
CMSTDAT_DTS    38
CMENDAT        32
CMENDAT_DTR    32
CMENDAT_DTS    32
CMONGO          2
CMONGO_C        2
CMONGO_ND       0
COMPTERM       42
CMDECOD        41
SITENO          7
dtype: int64

In [46]:
Concomitant_Medications.isnull().sum()

STUDYID         0
SITEID          0
SUBJID          0
SUBJECTID       0
VISITID         0
VISITIDX        0
VISITNAM        0
FORMNAME        0
FORMID          0
FORMIDX         0
FORMINDEX       0
CMYN            0
CMYN_C          0
CMCAT_C         0
CMCAT_ND       50
CMSCAT         50
CMSCAT_C       50
CMPRESP         0
CMPRESP_C       0
CMPRESP_ND     50
CMTRT           0
CMTRT_ND       50
CMRGM          50
CMRGM_ND       50
CMINDC         50
CMAENO         40
CMAER           0
CMAER_C         0
CMDOSTOT       22
CMDOSTOT_ND    50
CMDOSU         22
CMDOSU_C       22
CMDOSU_ND      50
CMROUTE        50
CMROUTE_C      50
CMPRIOR         0
CMPRIOR_C       0
CMSTDAT         4
CMSTDAT_DTR     0
CMSTDAT_DTS     0
CMENDAT        10
CMENDAT_DTR    10
CMENDAT_DTS    10
CMONGO          0
CMONGO_C        0
CMONGO_ND      50
COMPTERM        0
CMDECOD         0
SITENO          0
dtype: int64

# Common Problems(discrepancies) seen in this dataset

In AE dataset some column doesnt have any entry ex: DOV,(date of visit ) , whereas is CE dataset we can see many such null columns

In [65]:
Adverse_events.drop(columns=['DOV',
'AEREFID',
'AEREL1_ND',
'AETRT2_ND', 
'AEREL2_ND',
'AERELNST_ND'])

# these columns are removed because it doesn't have a single entry in its column

,STUDYID,SITEID,SUBJID,SUBJECTID,VISITINDEX,VISITNAM,FORMNAME,FORMID,FORMIDX,FORMINDEX,...,AEREL3,AEACN3_C,AEACN3,AEACN3_1_C,AEACN3_1,AERELNST_C,AERELNST,AERELT,AEOUT_C,AEOUT
0,StudyHack,5178,51785003,205861,1,AECM,AE203,38451,1,5.850000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,StudyHack,5178,51785001,156724,1,AECM,AE203,38451,1,5.520000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,StudyHack,5164,51645001,678844,1,AECM,AE203,38451,1,5.620000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,StudyHack,5521,55253014,11233277,1,AECM,AE203,38451,2,6.030000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,StudyHack,5521,55253014,11233277,1,AECM,AE203,38451,1,6.030000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,StudyHack,5525,55255001,2021912,1,AECM,AE203_2,38519,1,5.950000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,StudyHack,5035,50355004,604835,1,AECM,AE203_2,38519,1,5.640000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,StudyHack,5065,50655009,6444680,1,AECM,AE203_2,38519,1,6.060000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,StudyHack,5082,50825001,3010754,1,AECM,AE203_2,38519,1,5.740000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,StudyHack,5167,51675001,299197,1,AECM,AE203,38451,1,5.880000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,StudyHack,5117,51175004,10433285,1,AECM,AE203,38451,4,6.030000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,StudyHack,5117,51175004,10433285,1,AECM,AE203,38451,3,6.030000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,StudyHack,5117,51175004,10433285,1,AECM,AE203,38451,2,6.030000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,StudyHack,5117,51175004,10433285,1,AECM,AE203,38451,1,6.030000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,StudyHack,5094,50945001,2317067,1,AECM,AE203_2,38519,5,5.950000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,StudyHack,5094,50945001,2317067,1,AECM,AE203_2,38519,4,5.950000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,StudyHack,5094,50945001,2317067,1,AECM,AE203_2,38519,3,5.950000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,StudyHack,5094,50945001,2317067,1,AECM,AE203_2,38519,2,5.950000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,StudyHack,5094,50945001,2317067,1,AECM,AE203_2,38519,1,5.950000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,StudyHack,5094,50945001,2317067,1,AECM,AE203_2,38519,8,6.090000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,StudyHack,5094,50945001,2317067,1,AECM,AE203_2,38519,7,6.090000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,StudyHack,5094,50945001,2317067,1,AECM,AE203_2,38519,6,6.000000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,StudyHack,5149,51495003,4286167,1,AECM,AE203,38451,1,5.810000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,StudyHack,5094,50945007,8903544,1,AECM,AE203_2,38519,1,6.000000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,StudyHack,5177,51775003,1168790,1,AECM,AE203,38451,1,6.050000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,StudyHack,5063,50635001,12013064,1,AECM,AE203,38451,1,5.920000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,StudyHack,5179,51795013,5064159,1,AECM,AE203_2,38519,2,5.840000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,StudyHack,5179,51795013,5064159,1,AECM,AE203_2,38519,1,5.840000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,StudyHack,5185,51855001,11332935,1,AECM,AE203,38451,3,6.030000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,StudyHack,5185,51855001,11332935,1,AECM,AE203,38451,2,6.030000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,StudyHack,5185,51855001,11332935,1,AECM,AE203,38451,1,5.910000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,StudyHack,5114,51145007,5115151,1,AECM,AE203,38451,1,6.150000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,StudyHack,5065,50655006,5276455,1,AECM,AE203,38451,1,5.980000e+14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,StudyHack,5538,55385052,2978591,1,AECM,AE202,38768,13,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
34,StudyHack,5538,55385052,2978591,1,AECM,AE202,38768,15,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
35,StudyHack,5538,55385052,2978591,1,AECM,AE202,38768,19,5.840000e+14,...,NOT RELATED,NaN,NaN,2.0,DOSE NOT CHANGED,3.0,OTHER,primary disease,3.0,RECOVERED/RESOLVED
36,StudyHack,5538,55385051,1898906,1,AECM,AE202,38768,40,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
37,StudyHack,5538,55385051,1898906,1,AECM,AE202,38768,41,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
38,StudyHack,5538,55385051,1898906,1,AECM,AE202,38768,42,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
39,StudyHack,5538,55385051,1898906,1,AECM,AE202,38768,43,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
40,StudyHack,5538,55385051,1898906,1,AECM,AE202,38768,44,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
41,StudyHack,5538,55385051,1898906,1,AECM,AE202,38768,45,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
42,StudyHack,5538,55385051,1898906,1,AECM,AE202,38768,46,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
43,StudyHack,5538,55385052,2978591,1,AECM,AE202,38768,30,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
44,StudyHack,5538,55385052,2978591,1,AECM,AE202,38768,31,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
45,StudyHack,5538,55385052,2978591,1,AECM,AE202,38768,32,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
46,StudyHack,5538,55385052,2978591,1,AECM,AE202,38768,33,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
47,StudyHack,5538,55385052,2978591,1,AECM,AE202,38768,34,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED
48,StudyHack,5538,55385052,2978591,1,AECM,AE202,38768,35,5.840000e+14,...,RELATED,2.0,DOSE NOT CHANGED,NaN,NaN,NaN,NaN,NaN,3.0,RECOVERED/RESOLVED

In [71]:
Adverse_events["AESTDAT_DTS"].isnull().sum()
# two null values in ADverse event

2

In [88]:
#Concomitant_Medications["CMSTDAT_DTR"].isnull().sum()
Concomitant_Medications["CMSTDAT_DTR"]

0      21/09/2018
1      50/30/2018
2       51/5/2018
3       50/9/2018
4      50/22/2018
5      08/09/2018
6      26/09/2018
7       50/2/2018
8       50/2/2018
9      16/08/2018
10      51/5/2019
11      51/1/2019
12     50/21/2019
13     51/50/2019
14     50/28/2019
15     22/08/2018
16     17/09/2018
17     25/07/2018
18      9/52/2018
19     04/09/2018
20     08/09/2018
21     17/02/2020
22     17/02/2020
23     18/02/2020
24     21/02/2020
25     21/02/2020
26     09/03/2020
27     09/03/2020
28     09/03/2020
29     09/03/2020
30     30/07/2019
31     24/07/2019
32      7/53/2019
33     07/07/2019
34     04/09/2019
35     07/09/2019
36     08/09/2019
37     08/09/2019
38     08/09/2019
39     51/53/2018
40     51/53/2018
41    2019/51/UNK
42      51/4/2019
43     51/14/2019
44      51/3/2019
45    2019/51/UNK
46    2019/51/UNK
47      51/7/2019
48    2019/52/UNK
49     05/01/2020
Name: CMSTDAT_DTR, dtype: object

compare the start date of adverse effect and Medication start date

AE = AESTDAT_DTS  CE = CMSTDAT_DTR

In [147]:
frame = { 'AE':Adverse_events["AESTDAT_DTS"] , 'CE':Concomitant_Medications["CMSTDAT_DTR"],"AETERM":Adverse_events["AETERM"] } 
  
result_date = pd.DataFrame(frame)

In [148]:
result_date

            AE           CE                                             AETERM
0   17/08/2018   21/09/2018  A HIGHER DOSE LEVEL GIVEN FOR CYCLE 1 CONSOLID...
1   01/07/2018   50/30/2018                                   PUMP MALFUNCTION
2   02/10/2018    51/5/2018               INCORRECT STUDY MEDICATION DISPENSED
3   28/11/2019    50/9/2018                        Study Drug Dispensing Error
4   18/11/2019   50/22/2018                        Study Drug Dispensing Error
5   12/08/2019   08/09/2018  patient dosed with 135mg Studydrug2 instead of...
6          NaN   26/09/2018                                                NaN
7   08/07/2019    50/2/2018  Half of Studydrug2 dose was missed on C1D5(aft...
8          NaN    50/2/2018                                                NaN
9   30/07/2018   16/08/2018                        STUDY DRUG DISPENSING ERROR
10  29/10/2019    51/5/2019                        STUDY DRUG DISPENSING ERROR
11  22/10/2019    51/1/2019                        STUDY DRUG DISPENSING ERROR
12  07/10/2019   50/21/2019                        STUDY DRUG DISPENSING ERROR
13  27/09/2019   51/50/2019                        STUDY DRUG DISPENSING ERROR
14  26/08/2019   50/28/2019             SCHEDULED DOSING TAKEN LESS FREQUENTLY
15  29/07/2019   22/08/2018             SCHEDULED DOSING TAKEN LESS FREQUENTLY
16  01/07/2019   17/09/2018             SCHEDULED DOSING TAKEN LESS FREQUENTLY
17  03/06/2019   25/07/2018             SCHEDULED DOSING TAKEN LESS FREQUENTLY
18  07/05/2019    9/52/2018             SCHEDULED DOSING TAKEN LESS FREQUENTLY
19  18/11/2019   04/09/2018             SCHEDULED DOSING TAKEN LESS FREQUENTLY
20  21/10/2019   08/09/2018             SCHEDULED DOSING TAKEN LESS FREQUENTLY
21  23/09/2019   17/02/2020             SCHEDULED DOSING TAKEN LESS FREQUENTLY
22  25/04/2019   17/02/2020             INCORRECT DRUG ADMINISTRATION DURATION
23  16/10/2019   18/02/2020             SCHEDULED DOSING TAKEN LESS FREQUENTLY
24  26/02/2019   21/02/2020                        Study drug dispensing error
25  24/09/2019   21/02/2020  Tech. error Infusomat inlet velocity set to 21...
26  24/06/2019   09/03/2020                                       MISSED DOSES
27  18/06/2019   09/03/2020            MULTIPLE DOSES TAKEN PER DAY - OVERDOSE
28  16/01/2020   09/03/2020                        STUDY DRUG DISPENSING ERROR
29  16/01/2020   09/03/2020                        STUDY DRUG DISPENSING ERROR
30  23/09/2019   30/07/2019                                TOOK ONE EXTRA DOSE
31  19/06/2019   24/07/2019                          Extra dose taken in error
32  25/10/2019    7/53/2019  the dose administered after progression by sub...
33  15/04/2019   07/07/2019                         WHITE BLOOD CELL DECREASED
34  11/03/2019   04/09/2019                                        NEUTROPENIA
35  09/03/2019   07/09/2019                                             ANEMIA
36  13/02/2019   08/09/2019                         WHITE BLOOD CELL DECREASED
37  15/02/2019   08/09/2019                         WHITE BLOOD CELL DECREASED
38  20/02/2019   08/09/2019                         WHITE BLOOD CELL DECREASED
39  14/03/2019   51/53/2018                         WHITE BLOOD CELL DECREASED
40  15/03/2019   51/53/2018                         WHITE BLOOD CELL DECREASED
41  18/03/2019  2019/51/UNK                         WHITE BLOOD CELL DECREASED
42  22/03/2019    51/4/2019                         WHITE BLOOD CELL DECREASED
43  13/03/2019   51/14/2019                                   THROMBOCYTOPENIA
44  15/03/2019    51/3/2019                                   THROMBOCYTOPENIA
45  29/03/2019  2019/51/UNK                                   THROMBOCYTOPENIA
46  01/04/2019  2019/51/UNK                                   THROMBOCYTOPENIA
47  05/04/2019    51/7/2019                                   THROMBOCYTOPENIA
48  08/04/2019  2019/52/UNK                                   THROMBOCYTOPENIA
49         NaN   05/01/2020                                                NaN

# we can see discripancies in the medication data  !!!!!!!

In [98]:
result_date[39:49]

            AE           CE
39  14/03/2019   51/53/2018
40  15/03/2019   51/53/2018
41  18/03/2019  2019/51/UNK
42  22/03/2019    51/4/2019
43  13/03/2019   51/14/2019
44  15/03/2019    51/3/2019
45  29/03/2019  2019/51/UNK
46  01/04/2019  2019/51/UNK
47  05/04/2019    51/7/2019
48  08/04/2019  2019/52/UNK

Comparing the AE identifier and medication indentifier

In [143]:
frame_1 = { 'AE':Adverse_events["AESPID"] , 'CE':Concomitant_Medications["CMAENO"],"AETERM":Adverse_events["AETERM"] } 
  
result_id = pd.DataFrame(frame_1)

In [144]:
result_id

      AE    CE                                             AETERM
0    NaN   NaN  A HIGHER DOSE LEVEL GIVEN FOR CYCLE 1 CONSOLID...
1    NaN   NaN                                   PUMP MALFUNCTION
2    NaN   NaN               INCORRECT STUDY MEDICATION DISPENSED
3    NaN   NaN                        Study Drug Dispensing Error
4    NaN   NaN                        Study Drug Dispensing Error
5    NaN   NaN  patient dosed with 135mg Studydrug2 instead of...
6    NaN   NaN                                                NaN
7    NaN   NaN  Half of Studydrug2 dose was missed on C1D5(aft...
8    NaN   NaN                                                NaN
9    NaN   NaN                        STUDY DRUG DISPENSING ERROR
10   NaN  19.0                        STUDY DRUG DISPENSING ERROR
11   NaN  22.0                        STUDY DRUG DISPENSING ERROR
12   NaN  24.0                        STUDY DRUG DISPENSING ERROR
13   NaN   NaN                        STUDY DRUG DISPENSING ERROR
14   NaN   NaN             SCHEDULED DOSING TAKEN LESS FREQUENTLY
15   NaN   NaN             SCHEDULED DOSING TAKEN LESS FREQUENTLY
16   NaN   3.0             SCHEDULED DOSING TAKEN LESS FREQUENTLY
17   NaN   NaN             SCHEDULED DOSING TAKEN LESS FREQUENTLY
18   NaN   4.0             SCHEDULED DOSING TAKEN LESS FREQUENTLY
19   NaN   1.0             SCHEDULED DOSING TAKEN LESS FREQUENTLY
20   NaN   2.0             SCHEDULED DOSING TAKEN LESS FREQUENTLY
21   NaN  41.0             SCHEDULED DOSING TAKEN LESS FREQUENTLY
22   NaN  42.0             INCORRECT DRUG ADMINISTRATION DURATION
23   NaN   NaN             SCHEDULED DOSING TAKEN LESS FREQUENTLY
24   NaN  18.0                        Study drug dispensing error
25   NaN   NaN  Tech. error Infusomat inlet velocity set to 21...
26   NaN   NaN                                       MISSED DOSES
27   NaN   NaN            MULTIPLE DOSES TAKEN PER DAY - OVERDOSE
28   NaN   NaN                        STUDY DRUG DISPENSING ERROR
29   NaN   NaN                        STUDY DRUG DISPENSING ERROR
30   NaN   NaN                                TOOK ONE EXTRA DOSE
31   NaN   NaN                          Extra dose taken in error
32   NaN   NaN  the dose administered after progression by sub...
33  13.0   NaN                         WHITE BLOOD CELL DECREASED
34  15.0   NaN                                        NEUTROPENIA
35  19.0   NaN                                             ANEMIA
36  40.0   NaN                         WHITE BLOOD CELL DECREASED
37  41.0   NaN                         WHITE BLOOD CELL DECREASED
38  42.0   NaN                         WHITE BLOOD CELL DECREASED
39  43.0   NaN                         WHITE BLOOD CELL DECREASED
40  44.0   NaN                         WHITE BLOOD CELL DECREASED
41  45.0   NaN                         WHITE BLOOD CELL DECREASED
42  46.0   NaN                         WHITE BLOOD CELL DECREASED
43  30.0   NaN                                   THROMBOCYTOPENIA
44  31.0   NaN                                   THROMBOCYTOPENIA
45  32.0   NaN                                   THROMBOCYTOPENIA
46  33.0   NaN                                   THROMBOCYTOPENIA
47  34.0   NaN                                   THROMBOCYTOPENIA
48  35.0   NaN                                   THROMBOCYTOPENIA
49   NaN   NaN                                                NaN

There is no proper data in both AE identifier and Medication id to find the right Adverse event

0     21-Aug-18
1     01-Jul-18
2     08-Oct-18
3     03-Dec-19
4     28-Nov-19
5     20-Aug-19
6           NaN
7     08-Jul-19
8           NaN
9     09-Aug-18
10    05-Nov-19
11    29-Oct-19
12    22-Oct-19
13    07-Oct-19
14    22-Sep-19
15    25-Aug-19
16    28-Jul-19
17    30-Jun-19
18    02-Jun-19
19    15-Dec-19
20    17-Nov-19
21    20-Oct-19
22    25-Apr-19
23    12-Nov-19
24    07-Mar-19
25    24-Sep-19
26    26-Jun-19
27    23-Jun-19
28    30-Jan-20
29    30-Jan-20
30    23-Sep-19
31    19-Jun-19
32    28-Oct-19
33    22-Apr-19
34    13-Mar-19
35    13-Mar-19
36    15-Feb-19
37    20-Feb-19
38    14-Mar-19
39    15-Mar-19
40    18-Mar-19
41    22-Mar-19
42    13-Apr-19
43    15-Mar-19
44    29-Mar-19
45    01-Apr-19
46    05-Apr-19
47    08-Apr-19
48    10-Apr-19
Name: AEENDAT, dtype: object

In [145]:
frame_1 = { 'AE':Adverse_events["AESTDAT"] , 'AE_1':Adverse_events["AEENDAT"],"AETERM":Adverse_events["AETERM"]} 
  
result_co = pd.DataFrame(frame_1)

In [146]:
result_co

           AE       AE_1                                             AETERM
0   17-Aug-18  21-Aug-18  A HIGHER DOSE LEVEL GIVEN FOR CYCLE 1 CONSOLID...
1   01-Jul-18  01-Jul-18                                   PUMP MALFUNCTION
2   02-Oct-18  08-Oct-18               INCORRECT STUDY MEDICATION DISPENSED
3   28-Nov-19  03-Dec-19                        Study Drug Dispensing Error
4   18-Nov-19  28-Nov-19                        Study Drug Dispensing Error
5   12-Aug-19  20-Aug-19  patient dosed with 135mg Studydrug2 instead of...
6         NaN        NaN                                                NaN
7   08-Jul-19  08-Jul-19  Half of Studydrug2 dose was missed on C1D5(aft...
8         NaN        NaN                                                NaN
9   30-Jul-18  09-Aug-18                        STUDY DRUG DISPENSING ERROR
10  29-Oct-19  05-Nov-19                        STUDY DRUG DISPENSING ERROR
11  22-Oct-19  29-Oct-19                        STUDY DRUG DISPENSING ERROR
12  07-Oct-19  22-Oct-19                        STUDY DRUG DISPENSING ERROR
13  27-Sep-19  07-Oct-19                        STUDY DRUG DISPENSING ERROR
14  26-Aug-19  22-Sep-19             SCHEDULED DOSING TAKEN LESS FREQUENTLY
15  29-Jul-19  25-Aug-19             SCHEDULED DOSING TAKEN LESS FREQUENTLY
16  01-Jul-19  28-Jul-19             SCHEDULED DOSING TAKEN LESS FREQUENTLY
17  03-Jun-19  30-Jun-19             SCHEDULED DOSING TAKEN LESS FREQUENTLY
18  07-May-19  02-Jun-19             SCHEDULED DOSING TAKEN LESS FREQUENTLY
19  18-Nov-19  15-Dec-19             SCHEDULED DOSING TAKEN LESS FREQUENTLY
20  21-Oct-19  17-Nov-19             SCHEDULED DOSING TAKEN LESS FREQUENTLY
21  23-Sep-19  20-Oct-19             SCHEDULED DOSING TAKEN LESS FREQUENTLY
22  25-Apr-19  25-Apr-19             INCORRECT DRUG ADMINISTRATION DURATION
23  16-Oct-19  12-Nov-19             SCHEDULED DOSING TAKEN LESS FREQUENTLY
24  26-Feb-19  07-Mar-19                        Study drug dispensing error
25  24-Sep-19  24-Sep-19  Tech. error Infusomat inlet velocity set to 21...
26  24-Jun-19  26-Jun-19                                       MISSED DOSES
27  18-Jun-19  23-Jun-19            MULTIPLE DOSES TAKEN PER DAY - OVERDOSE
28  16-Jan-20  30-Jan-20                        STUDY DRUG DISPENSING ERROR
29  16-Jan-20  30-Jan-20                        STUDY DRUG DISPENSING ERROR
30  23-Sep-19  23-Sep-19                                TOOK ONE EXTRA DOSE
31  19-Jun-19  19-Jun-19                          Extra dose taken in error
32  25-Oct-19  28-Oct-19  the dose administered after progression by sub...
33  15-Apr-19  22-Apr-19                         WHITE BLOOD CELL DECREASED
34  11-Mar-19  13-Mar-19                                        NEUTROPENIA
35  09-Mar-19  13-Mar-19                                             ANEMIA
36  13-Feb-19  15-Feb-19                         WHITE BLOOD CELL DECREASED
37  15-Feb-19  20-Feb-19                         WHITE BLOOD CELL DECREASED
38  20-Feb-19  14-Mar-19                         WHITE BLOOD CELL DECREASED
39  14-Mar-19  15-Mar-19                         WHITE BLOOD CELL DECREASED
40  15-Mar-19  18-Mar-19                         WHITE BLOOD CELL DECREASED
41  18-Mar-19  22-Mar-19                         WHITE BLOOD CELL DECREASED
42  22-Mar-19  13-Apr-19                         WHITE BLOOD CELL DECREASED
43  13-Mar-19  15-Mar-19                                   THROMBOCYTOPENIA
44  15-Mar-19  29-Mar-19                                   THROMBOCYTOPENIA
45  29-Mar-19  01-Apr-19                                   THROMBOCYTOPENIA
46  01-Apr-19  05-Apr-19                                   THROMBOCYTOPENIA
47  05-Apr-19  08-Apr-19                                   THROMBOCYTOPENIA
48  08-Apr-19  10-Apr-19                                   THROMBOCYTOPENIA

#   Duplicates in the unique form ID

In [149]:
frame_1 = { 'form_id':Adverse_events["FORMID"] , 'form_idx':Adverse_events["FORMIDX"],"form_index":Adverse_events["FORMINDEX"]} 
  
result_form = pd.DataFrame(frame_1)

In [150]:
result_form

    form_id  form_idx    form_index
0     38451         1  5.850000e+14
1     38451         1  5.520000e+14
2     38451         1  5.620000e+14
3     38451         2  6.030000e+14
4     38451         1  6.030000e+14
5     38519         1  5.950000e+14
6     38519         1  5.640000e+14
7     38519         1  6.060000e+14
8     38519         1  5.740000e+14
9     38451         1  5.880000e+14
10    38451         4  6.030000e+14
11    38451         3  6.030000e+14
12    38451         2  6.030000e+14
13    38451         1  6.030000e+14
14    38519         5  5.950000e+14
15    38519         4  5.950000e+14
16    38519         3  5.950000e+14
17    38519         2  5.950000e+14
18    38519         1  5.950000e+14
19    38519         8  6.090000e+14
20    38519         7  6.090000e+14
21    38519         6  6.000000e+14
22    38451         1  5.810000e+14
23    38519         1  6.000000e+14
24    38451         1  6.050000e+14
25    38451         1  5.920000e+14
26    38519         2  5.840000e+14
27    38519         1  5.840000e+14
28    38451         3  6.030000e+14
29    38451         2  6.030000e+14
30    38451         1  5.910000e+14
31    38451         1  6.150000e+14
32    38451         1  5.980000e+14
33    38768        13  5.840000e+14
34    38768        15  5.840000e+14
35    38768        19  5.840000e+14
36    38768        40  5.840000e+14
37    38768        41  5.840000e+14
38    38768        42  5.840000e+14
39    38768        43  5.840000e+14
40    38768        44  5.840000e+14
41    38768        45  5.840000e+14
42    38768        46  5.840000e+14
43    38768        30  5.840000e+14
44    38768        31  5.840000e+14
45    38768        32  5.840000e+14
46    38768        33  5.840000e+14
47    38768        34  5.840000e+14
48    38768        35  5.840000e+14

In [151]:
result_form[33:48]

    form_id  form_idx    form_index
33    38768        13  5.840000e+14
34    38768        15  5.840000e+14
35    38768        19  5.840000e+14
36    38768        40  5.840000e+14
37    38768        41  5.840000e+14
38    38768        42  5.840000e+14
39    38768        43  5.840000e+14
40    38768        44  5.840000e+14
41    38768        45  5.840000e+14
42    38768        46  5.840000e+14
43    38768        30  5.840000e+14
44    38768        31  5.840000e+14
45    38768        32  5.840000e+14
46    38768        33  5.840000e+14
47    38768        34  5.840000e+14

We can see the descripancies in the form index and form idx where form idx should be same for certain form